#!/usr/bin/env python3
"""Generate IDs from the content hashes of the built-in UI font headers."""

import hashlib
from pathlib import Path


FONT_DIR = Path(__file__).resolve().parent.parent / "builtinFonts"
UI_HEADER = ("pretendard_10_regular.h",)


def font_id(headers):
    digest_sum = sum(int(hashlib.sha256((FONT_DIR / name).read_bytes()).hexdigest(), 16) for name in headers)
    return digest_sum % (2**32) - (2**31)


print("// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh")
print("#pragma once\n")
print(f"#define UI_FONT_ID ({font_id(UI_HEADER)})")
for name in ("SMALL_FONT_ID", "UI_10_FONT_ID", "UI_12_FONT_ID", "UI_18_FONT_ID"):
    print(f"#define {name} UI_FONT_ID")
print('\n// Font ID 0 is reserved as the "not found" sentinel.')
print("// Guard against any hash accidentally producing 0.")
print('static_assert(UI_FONT_ID != 0, "Font ID collision with sentinel");')
